// 头像池：312 枚 Fluent Emoji 3D 图标（微软 fluentui-emoji，MIT 许可，见 web/public/avatars/NOTICE.md）
// id 即文件名：web/public/avatars/<id>.png；分类仅用于选择器分组展示
export const AVATAR_CATEGORIES = [
  { id: 'person', name: '人物', items: ['astronaut','baby','baby_chick','boy','breast_feeding','child','construction_worker','cook','cooked_rice','cookie','cooking','farmer','firefighter','girl','guard','hugging_face','judge','man_artist','man_beard','man_construction_worker','man_curly_hair','man_police_officer','man_red_hair','man_scientist','man_student','man_teacher','man_technologist','man_white_hair','mechanic','office_worker','old_woman','older_person','person_beard','person_curly_hair','person_red_hair','pilot','pregnant_woman','woman_artist','woman_construction_worker','woman_curly_hair','woman_police_officer','woman_red_hair','woman_scientist','woman_student','woman_teacher','woman_technologist'] },
  { id: 'animal', name: '动物', items: ['badger','bat','bear','beaver','beetle','bird','black_cat','blackbird','blowfish','boar','bug','butterfly','camel','cat','cat_face','chicken','chipmunk','cow_face','crab','cricket','crocodile','deer','dodo','dog','dog_face','dolphin','donkey','dove','dragon_face','duck','eagle','elephant','ewe','fish','flamingo','fox','frog','front_facing_baby_chick','giraffe','goat','goose','gorilla','hamster','hatching_chick','hedgehog','hippopotamus','honeybee','horse','horse_face','jellyfish','kangaroo','koala','lady_beetle','leopard','lion','lizard','llama','lobster','mammoth','monkey','moose','orangutan','otter','owl','oyster','panda','parrot','paw_prints','peacock','penguin','phoenix_bird','pig','pig_face','polar_bear','poodle','rabbit_face','raccoon','ram','rhinoceros','rooster','sauropod','seal','shark','shrimp','skunk','sloth','snail','spouting_whale','squid','swan','t_rex','tiger','tropical_fish','turtle','two_hump_camel','unicorn','whale','zebra'] },
  { id: 'food', name: '食物', items: ['avocado','bagel','baguette_bread','banana','bento_box','beverage_box','birthday_cake','blueberries','bread','broccoli','brown_mushroom','bubble_tea','burrito','butter','candy','canned_food','cheese_wedge','cherries','chestnut','chocolate_bar','coconut','croissant','cupcake','curry_rice','custard','dango','doughnut','dumpling','ear_of_corn','egg','eggplant','falafel','flatbread','fondue','french_fries','fried_shrimp','grapes','green_apple','hamburger','honey_pot','hot_beverage','hot_dog','hot_pepper','ice_cream','kiwi_fruit','leafy_green','lemon','lime','lollipop','mango','melon','moon_cake','mushroom','pea_pod','peach','peanuts','pear','pineapple','pizza','popcorn','pot_of_food','pretzel','red_apple','rice_ball','rice_cracker','roasted_sweet_potato','sandwich','shallow_pan_of_food','shaved_ice','sheaf_of_rice','shortcake','soft_ice_cream','spaghetti','strawberry','stuffed_flatbread','sushi','taco','takeout_box','tamale','tangerine','teacup_without_handle','tomato','tropical_drink','watermelon'] },
  { id: 'other', name: '自然与物品', items: ['accordion','balloon','banjo','beach_with_umbrella','blossom','bouquet','bubbles','cactus','camping','cherry_blossom','chess_pawn','comet','coral','cyclone','deciduous_tree','desert','desert_island','diya_lamp','droplet','empty_nest','evergreen_tree','feather','fire','fireworks','first_quarter_moon','first_quarter_moon_face','flute','four_leaf_clover','framed_picture','full_moon','full_moon_face','glowing_star','graduation_cap','guitar','herb','hibiscus','high_voltage','hyacinth','ice','jack_o_lantern','kite','last_quarter_moon','lotus','milky_way','moon_viewing_ceremony','mountain','national_park','nest_with_eggs','palm_tree','pine_decoration','postal_horn','potted_plant','rainbow','ringed_planet','rocket','rosette','saxophone','seedling','shamrock','shooting_star','snow_capped_mountain','snowflake','snowman','sparkler','sparkles','star','sun','sun_behind_cloud','sun_with_face','sunflower','tanabata_tree','teddy_bear','tent','tornado','trumpet','tulip','umbrella_on_ground','violin','volcano','water_wave','wind_chime','wind_face','wing','yarn'] },
]

export const AVATAR_IDS = new Set(AVATAR_CATEGORIES.flatMap(c => c.items))

export function isKnownAvatar(v) {
  return typeof v === 'string' && AVATAR_IDS.has(v)
}

export function avatarSrc(id) {
  return '/avatars/' + id + '.png'
}
